"""
Delta updater — downloads and applies a patch ZIP to the running app.

The patch ZIP contains only the changed .py files (generated by
scripts/generate_patch.py).  Applying it is fast because:
  • Download: ~100 KB instead of ~90 MB
  • Apply:    just extract + overwrite a handful of .py files
  • Restart:  same process command, restarted in-place

Supports two runtime modes:
  source  — running as `python frontend/main.py`  (dev / direct install)
  frozen  — running as PyInstaller .exe           (full installed build)

In frozen (onefile) mode the patch is stored next to the .exe so the
*next* run picks it up via sys.path injection (see packaging/runtime_hook_pyqt6.py).
In source mode the patch is extracted directly on top of the source tree.
"""

from __future__ import annotations

import hashlib
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path
from typing import Optional

import requests
import errno
import getpass

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# App-root detection
# ---------------------------------------------------------------------------

def detect_app_root() -> Path:
    """Return the directory that contains the app's .py source files."""
    if getattr(sys, "frozen", False):
        # PyInstaller: executable lives in the install dir; patches go there too
        return Path(sys.executable).resolve().parent
    else:
        # Source mode: two levels up from this file (updater/delta_updater.py → project root)
        return Path(__file__).resolve().parent.parent


def is_frozen() -> bool:
    return getattr(sys, "frozen", False)


# ---------------------------------------------------------------------------
# Download helpers
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def download_file(url: str, dest: Path, on_progress=None) -> Path:
    """Download *url* to *dest*, calling on_progress(downloaded_bytes, total_bytes) if provided."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    with requests.get(url, stream=True, timeout=60) as r:
        r.raise_for_status()
        total = int(r.headers.get("content-length", 0))
        downloaded = 0
        with open(dest, "wb") as f:
            for chunk in r.iter_content(65536):
                if chunk:
                    f.write(chunk)
                    downloaded += len(chunk)
                    if on_progress and total:
                        on_progress(downloaded, total)
    return dest


# ---------------------------------------------------------------------------
# Patch application
# ---------------------------------------------------------------------------

def apply_patch_zip(zip_path: Path, app_root: Path) -> list[str]:
    """
    Extract *zip_path* into *app_root*.

    For source mode:  overwrites .py files directly in the source tree.
    For frozen mode:  extracts into a `_src_patches/` sibling directory next
                      to the .exe; the runtime hook adds that to sys.path[0]
                      so patched modules shadow the compiled ones.

    Returns the list of files that were applied.
    """
    if is_frozen():
        # Side-car patches directory next to the .exe (may be under Program Files)
        extract_root = app_root / "_src_patches"
        # Proactively test whether we can write into the install dir.
        try:
            test_dir = extract_root / ".write_test"
            test_dir.parent.mkdir(parents=True, exist_ok=True)
            with open(test_dir, 'w') as tf:
                tf.write('ok')
            try:
                test_dir.unlink()
            except Exception:
                pass
        except Exception:
            # Not writable — use LocalAppData fallback immediately
            logger.info(f"Install dir not writable: {extract_root}; using LocalAppData fallback for patches")
            try:
                local_base = Path(os.getenv('LOCALAPPDATA') or Path.home() / 'AppData' / 'Local')
                app_name = "Streamore Monitor" # Stable name for LocalAppData
                extract_root = local_base / app_name / '_src_patches'
                extract_root.mkdir(parents=True, exist_ok=True)
                logger.info(f"Using LocalAppData patches: {extract_root}")
            except Exception as e:
                logger.warning(f"Failed to create LocalAppData fallback folder: {e}")
    else:
        extract_root = app_root

    applied: list[str] = []

    with zipfile.ZipFile(zip_path, "r") as zf:
        for info in zf.infolist():
            # Skip directories and __pycache__
            if info.filename.endswith("/") or "__pycache__" in info.filename:
                continue
            target = extract_root / info.filename
            target.parent.mkdir(parents=True, exist_ok=True)
            try:
                with zf.open(info) as src, open(target, "wb") as dst:
                    dst.write(src.read())
            except (PermissionError, OSError) as e:
                # If writing to the chosen extract_root fails here, attempt LocalAppData fallback.
                logger.warning(f"Permission writing {target}: {e}; attempting LocalAppData fallback")
                try:
                    local_base = Path(os.getenv('LOCALAPPDATA') or Path.home() / 'AppData' / 'Local')
                    app_name = "Streamore Monitor"
                    fallback_root = local_base / app_name / '_src_patches'
                    fallback_root.mkdir(parents=True, exist_ok=True)
                    # Extract remaining entries into fallback_root
                    for info2 in zf.infolist():
                        if info2.filename.endswith("/") or "__pycache__" in info2.filename:
                            continue
                        t2 = fallback_root / info2.filename
                        t2.parent.mkdir(parents=True, exist_ok=True)
                        with zf.open(info2) as s2, open(t2, "wb") as d2:
                            d2.write(s2.read())
                        applied.append(info2.filename)
                        logger.debug(f"Patched (fallback): {info2.filename}")
                    extract_root = fallback_root
                    break
                except Exception as e2:
                    logger.error(f"Failed to apply patch to fallback location: {e2}")
                    raise
            else:
                applied.append(info.filename)
                logger.debug(f"Patched: {info.filename}")

    # Wipe __pycache__ so Python recompiles from the fresh .py files
    for pycache in extract_root.rglob("__pycache__"):
        shutil.rmtree(pycache, ignore_errors=True)

    logger.info(f"Patch applied: {len(applied)} file(s) → {extract_root}")
    return applied


# ---------------------------------------------------------------------------
# Restart
# ---------------------------------------------------------------------------

def restart_app() -> None:
    """Re-execute the current process with the same arguments."""
    logger.info("Restarting app to apply patch…")
    
    # Clean environment to prevent sticky variables across restarts (e.g. old _MEI paths)
    env = os.environ.copy()
    # PyInstaller internal paths change on restart; don't inherit them
    env.pop('_MEIPASS', None)
    # Clear SSL variables so the NEW process's runtime hook can set them correctly
    env.pop('SSL_CERT_FILE', None)
    env.pop('REQUESTS_CA_BUNDLE', None)
    # Clear version override to ensure new code's version is picked up
    env.pop('APP_VERSION', None)
    # Clear delta patch path to allow the fresh process to re-detect it
    env.pop('APP_PATCH_PATH', None)

    if is_frozen():
        # Launch the .exe
        exe = Path(sys.executable)
        subprocess.Popen([str(exe)] + sys.argv[1:], cwd=str(exe.parent), env=env)
    else:
        # Re-launch with the same Python interpreter and argv
        subprocess.Popen([sys.executable] + sys.argv, cwd=str(detect_app_root()), env=env)
    # Exit current process
    sys.exit(0)



# ---------------------------------------------------------------------------
# High-level entry point
# ---------------------------------------------------------------------------

def apply_delta_update(
    manifest: dict,
    hmac_key: Optional[bytes] = None,
    on_progress=None,
) -> dict:
    """
    Download and apply the patch described in *manifest*.

    Returns a dict:
      {
        "is_patch": True,
        "version":  "1.0.12",
        "files":    ["backend/app.py", ...],
        "zip_path": "/tmp/patch_v1.0.12.zip",
      }

    Raises ValueError if the manifest has no patch_url.
    Raises RuntimeError if SHA256 verification fails.
    """
    patch_url = manifest.get("patch_url")
    patch_sha256 = manifest.get("patch_sha256")

    if not patch_url:
        raise ValueError("Manifest does not contain a patch_url — use full update instead")

    version = manifest.get("version", "unknown")
    zip_name = patch_url.rstrip("/").split("/")[-1]

    # Download to a temp file
    tmp_dir = Path(tempfile.mkdtemp(prefix="streamore_patch_"))
    zip_path = tmp_dir / zip_name

    logger.info(f"Downloading patch {zip_name} from {patch_url}")
    download_file(patch_url, zip_path, on_progress=on_progress)

    # Verify checksum
    if patch_sha256:
        actual = sha256_file(zip_path)
        if actual != patch_sha256:
            zip_path.unlink(missing_ok=True)
            raise RuntimeError(
                f"Patch SHA256 mismatch!\n  expected: {patch_sha256}\n  got:      {actual}"
            )

    # Apply
    app_root = detect_app_root()
    applied_files = apply_patch_zip(zip_path, app_root)

    return {
        "is_patch": True,
        "version": version,
        "files": applied_files,
        "zip_path": str(zip_path),
    }
